/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
package org.gradle.demo.evolution

import org.gradle.demo.api.evolution.DynamicGroovyClient
import org.gradle.demo.api.evolution.JavaClient
import org.gradle.demo.api.evolution.StaticGroovyClient
import spock.lang.Specification

class AppTest extends Specification {
    def "old Java client works with old api"() {
        when:
        JavaClient.main()

        then:
        noExceptionThrown()
    }

    def "old static Groovy client works with old api"() {
        when:
        StaticGroovyClient.main()

        then:
        noExceptionThrown()
    }

    def "old dynamic Groovy client works with old api"() {
        when:
        DynamicGroovyClient.main()

        then:
        noExceptionThrown()
    }
}
