name: Gradle build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: 8
      - uses: gradle/actions/setup-gradle@v3
        with:
          arguments: build --scan
      - name: Archive artifacts
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: "**/build/reports/tests/**"
